//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public long Admin_Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<int> Roles { get; set; }
        public string Password { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IsDelete { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
