//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.Subscription_Payment = new HashSet<Subscription_Payment>();
        }
    
        public int Subscription_Id { get; set; }
        public string Title { get; set; }
        public int Days { get; set; }
    
        public virtual ICollection<Subscription_Payment> Subscription_Payment { get; set; }
    }
}
