//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCreamParlour.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Orders = new HashSet<Order>();
            this.Subscription_Payment = new HashSet<Subscription_Payment>();
        }

        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int User_Id { get; set; }

        [Required(ErrorMessage ="Please input your name")]
        [StringLength(50, MinimumLength = 3)]
        public string Name { get; set; }

        [Required(ErrorMessage ="Please input your contact")]
        [DataType(DataType.PhoneNumber, ErrorMessage ="Phone number invalid")]
        [Display(Name ="Phone number")]
        public string Contact { get; set; }

        [Required(ErrorMessage ="Please input your email")]
        [DataType(DataType.EmailAddress, ErrorMessage ="Email invalid")]

        public string Email { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name ="Registration time")]
        public int UserType { get; set; }   

        [Required]
        [StringLength(14, ErrorMessage ="chua du do dai")]
        public string Card_No { get; set; }
        public System.DateTime JoinDate { get; set; }
        public int IsActive { get; set; }
        public int IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription_Payment> Subscription_Payment { get; set; }

        public int limit = 15;

        [Display(Name = "Email")]
        public string EmailTrimmed
        {
            get
            {
                if (this.Email.Length > this.limit) return this.Email.Substring(0, this.limit) + "...";
                else return this.Email;
            }
        }
    }
}
