//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminRegister_IceCreamParlour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription_Payment
    {
        public int SubscriptionPayment_Id { get; set; }
        public int User_Id { get; set; }
        public int Subscription_Id { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual User User { get; set; }
    }
}
